services:
  caddy:
    container_name: daongil-prod-caddy
    image: daongil-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Caddy data (Certificates, etc.)
      - /root/workspace/DaonGil/data/caddy/data:/data
      - /root/workspace/DaonGil/data/caddy/config:/config
      - /root/workspace/DaonGil/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    container_name: daongil-prod-backend
    build:
      context: ../../
      dockerfile: docker/backend/Dockerfile.prod
    command: sh -c "python migrate.py && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    env_file:
      - ../../.env
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: daongil-prod-db
    image: postgres:15-alpine
    volumes:
      - /root/workspace/DaonGil/data/postgres:/var/lib/postgresql/data
    env_file:
      - ../../.env
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    container_name: daongil-prod-redis
    image: redis:alpine
    volumes:
      - /root/workspace/DaonGil/data/redis:/data
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    container_name: daongil-prod-minio
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    volumes:
      - /root/workspace/DaonGil/data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
